// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13GURZZ3DCYuPufwMMYnXdZFssd3XqKE',
    appId: '1:755096402472:web:4fd27a4c970ea68a47131d',
    messagingSenderId: '755096402472',
    projectId: 'notes-2ecf2',
    authDomain: 'notes-2ecf2.firebaseapp.com',
    storageBucket: 'notes-2ecf2.appspot.com',
    measurementId: 'G-JGE05C6QL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiFgNrvI1MpXPJPITtrhJCS9Z9PcOWpdQ',
    appId: '1:755096402472:android:bd67c1c403df6b0047131d',
    messagingSenderId: '755096402472',
    projectId: 'notes-2ecf2',
    storageBucket: 'notes-2ecf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkfsnX-4gb023ynnVXn5HtU-gwPIwftg',
    appId: '1:755096402472:ios:6b57637e4ee5a1ea47131d',
    messagingSenderId: '755096402472',
    projectId: 'notes-2ecf2',
    storageBucket: 'notes-2ecf2.appspot.com',
    iosBundleId: 'in.co.therj.notes.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkfsnX-4gb023ynnVXn5HtU-gwPIwftg',
    appId: '1:755096402472:ios:abbee34a910866de47131d',
    messagingSenderId: '755096402472',
    projectId: 'notes-2ecf2',
    storageBucket: 'notes-2ecf2.appspot.com',
    iosBundleId: 'in.co.therj.notes.notes.RunnerTests',
  );
}
